### PR TITLE
fix(config): Validation Logic for Configuration File Extension

### LINKED ISSUE #75: [config] Bug: Validation Logic for Configuration File Extension
[`ConfigurationParser.fromFile`][ref] is currently case-sensitive to file extension. Expectedly, it should not have been case-sensitive like both of its upstream dependencies which are not restricted to accepting only case-sensitive file extensions:

```dart
...
if (filePath.endsWith('.json')) {
...
} else if (filePath.endsWith('.yaml') || filePath.endsWith('.yml')) {
...
throw UnsupportedError('Unsupported file extension: $filePath');
```

This bug results in a crash while loading external configurations (JSON or YAML) from, for example, configuration files with a fully uppercase filename.

  [ref]: https://github.com/serverpod/cli_tools/blob/a811a6f5d397c0a028e47fa1a4e934e168a84fcd/packages/config/lib/src/config/configuration_parser.dart#L32

### PR DESCRIPTION
**Pull request by indraneel12**
## Resolves #75 

Its validation logic is no longer based on case-sensitive file extensions, as the corresponding upstream packages do support case-insensitivity. The new Test Cases validate this use-case, by checking all combinations of File Content and case-insensitive File Extension permutations.

### Old Behavior

Supported file extensions are case-sensitive:
Screenshot_20251021_070558

### New Behavior

Supported file extensions are not case-sensitive:
Screenshot_20251021_065044

## Features

- correct validation logic
- comprehensive test cases
- enhanced documentation

## Summary by CodeRabbit

* **New Features**
  * Configuration file extension detection is now case-insensitive for .json, .yaml, and .yml.

* **Bug Fixes**
  * Explicit errors for unsupported extensions added; invalid content now yields format errors; missing files produce argument errors.

* **Documentation**
  * Usage notes added describing expected inputs and possible exceptions when loading configs.

* **Tests**
  * Comprehensive tests added covering JSON/YAML parsing, valid/invalid content, supported/unsupported extensions (including case variants), and missing-file scenarios.

### CODE REVIEW

File: packages/config/test/config/config_file_load_test.dart [hunk 1]
```diff
@@ -0,0 +1,277 @@
...
+        File(_buildFilepath(fileFormat, fact, fileExtension))
+          ..createSync(recursive: true, exclusive: true)
+          ..writeAsStringSync(_mockContent[fileFormat]![fact]!);
+      }
+      File(_buildFilepath(fileFormat, fact, _anUnsupportedExtension))
+        ..createSync(recursive: true, exclusive: true)
+        ..writeAsStringSync(_mockContent[fileFormat]![fact]!);
+    }
+  });
+}
```
[the remark this answers is not in the document]
Comment (indraneel12) [reply packages/config/test/config/config_file_load_test.dart]: Fixed in an easier way: https://github.com/serverpod/cli_tools/pull/76/commits/0a24eec282c5ecb8f66824edf3882945263263ed

File: packages/config/lib/src/config/configuration_parser.dart [hunk 2]
```diff
@@ -29,15 +29,14 @@ abstract final class ConfigurationParser {
   }
 
   /// Parses a configuration from a file.
-  static ConfigurationSource fromFile(
-    final String filePath,
-  ) {
-    if (filePath.endsWith('.json')) {
+  static ConfigurationSource fromFile(final String filePath) {
+    final check = filePath.toLowerCase();
```
Comment (christerswahn) [inline packages/config/lib/src/config/configuration_parser.dart]: Nit: Suggest a more specific variable name like for example `lowercaseFilePath`.

File: packages/config/test/config/config_file_load_test.dart [hunk 3]
```diff
@@ -84,8 +84,8 @@ void _verifyMockFileExtensions() {
             0, (final prev, final curr) => prev + pow(2, curr.length)),
     'YAML extension samples must be mathematically sound.',
   );
-  print('Unique JSON extensions for testing: $jsonExtensionSamplesCount');
-  print('Unique YAML extensions for testing: $yamlExtensionSamplesCount');
+  // print('Unique JSON extensions for testing: $jsonExtensionSamplesCount');
+  // print('Unique YAML extensions for testing: $yamlExtensionSamplesCount');
```
Comment (christerswahn) [inline packages/config/test/config/config_file_load_test.dart]: Suggestion: Remove commented-out code.

**Review by christerswahn — APPROVED** [review]
Good job! LGTM!
